### ISSUE TITLE
Urban Dictionary + Voice API #3

### ISSUE THREAD

**Issue by shellyrgarner** [wjcooper91/project1#7]
User story: As a user, I want to be able to have the definition of words I input played back as audio
1. the response from the urban dictionary is passed back into a var
2. the var is then passed into the ajax query to be sent to the text to speech api
3. the response from the text to speech api is passed back into a div to be displayed to the screen as well as converted into audio
4. audio button is created to recall again, if desired

**Comment by wjcooper91** [comment]
Resolved
